import sys
import os

def sanitize(name):
    return name.replace('.', '_').replace('-', '_')

def main(input_path, output_path):
    filename = os.path.basename(input_path)
    varname = sanitize(filename)

    with open(input_path, "rb") as f:
        data = f.read()

    with open(output_path, "w") as f:
        f.write("// This file was auto-generated from '{}'\n".format(filename))
        f.write("// Do not edit this file manually.\n\n")
        f.write(f"#pragma once\n\n")
        f.write(f"#include <array>\n#include <cstdint>\n\n")
        f.write(f"constexpr std::array<uint8_t, {len(data)}> {varname} = {{\n")

        for i in range(0, len(data), 12):
            chunk = data[i:i+12]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {line},\n")

        f.write("};\n")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("python bin_to_header.py <input_file> <output_file>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])